Movie create controller
los-tucanes-de-la-web/api-backend pull request #18
Opened 2022-11-02 03:02 UTC by marioanhelo

2022-11-02 03:28 UTC, servo98 requested changes
mover las carpetas

2022-11-02 03:28 UTC, servo98 commented on routes/movieRoutes.js
> +import express from 'express';
la carpeta routes debe estar dentro de api

2022-11-02 03:28 UTC, servo98 commented on controllers/movieController.js
> +import Movie from '../models/Movie.js';
esto debe estar dentro de la carpeta api

2022-11-02 03:28 UTC, servo98 commented on api/api.js
> +//TODO:
falta registrar la ruta de movie create en la instancia principal de express

2022-11-03 00:58 UTC, marioanhelo commented
Ya se actualizó el archivo api.js con la ruta de crear movie

2022-11-03 01:31 UTC, servo98 requested changes

2022-11-03 01:31 UTC, servo98 commented on api/api.js
> +import movieRoutes from './routes/movieRoutes'
falta extensión js

2022-11-03 01:40 UTC, servo98 approved these changes

2022-11-03 01:40 UTC, merged