User get
los-tucanes-de-la-web/api-backend pull request #19
Opened 2022-11-02 03:23 UTC by angels36b

2022-11-02 03:31 UTC, servo98 requested changes

2022-11-02 03:31 UTC, servo98 commented on router/userRouter.js
> +import express from 'express';
mover dentro de la carpeta api

2022-11-02 03:31 UTC, servo98 commented on controller/userController.js
> +import User from "../models/user.js"
el nombre del archivo va con mayúsculas

2022-11-03 01:34 UTC, angels36b commented on router/userRouter.js
> +import express from 'express';
Cambiado

2022-11-03 01:34 UTC, angels36b commented on controller/userController.js
> +import User from "../models/user.js"
Actualizado

2022-11-03 02:18 UTC, servo98 requested changes

2022-11-03 02:18 UTC, servo98 commented on api/api.js
> +api.use('/router', userRouter );
remplazar con users

2022-11-03 02:18 UTC, servo98 commented on api/routes/userRouter.js
> +router.route('/users').get( userController.read )
como ya pusiste prefijo en el api.js quitar de aquí el users

2022-11-03 02:18 UTC, servo98 commented on api/controller/userController.js
> +import User from "../models/User.js"
cambiar carpeta a controllers

2022-11-03 02:21 UTC, angels36b commented on api/routes/userRouter.js
> +router.route('/users').get( userController.read )
prefijo actualizado

2022-11-03 02:21 UTC, angels36b commented on api/controller/userController.js
> +import User from "../models/User.js"
carpeta cambiado

2022-11-03 02:22 UTC, angels36b reviewed
cambios realizados

2022-11-03 02:53 UTC, servo98 approved these changes

2022-11-03 02:54 UTC, merged