Login Creation
los-tucanes-de-la-web/api-backend pull request #22
Opened 2022-11-02 03:29 UTC by Soyelchamps

2022-11-02 03:38 UTC, servo98 requested changes

2022-11-02 03:38 UTC, servo98 commented on package.json
> +    "bcrypt": "^5.1.0",
falta dependencia de dotenv

2022-11-02 03:38 UTC, servo98 commented on controllers/userControllers.js
> +import bcrypt from "bcrypt";
debe estar dentro de la carpeta api

2022-11-02 03:38 UTC, servo98 commented on controllers/userControllers.js
> +      userid: user.id,
userId camel case

2022-11-03 01:50 UTC, servo98 requested changes

2022-11-03 01:50 UTC, servo98 commented on controllers/userControllers.js
> +      if (!isVerified) {
sacar if del otro if y usar la propiedad isVerified dentro de user

2022-11-03 01:50 UTC, servo98 commented on controllers/userControllers.js
> +    const token = jwt.encode(payload, config.jwtSecret);
crear jwtSecret dentro de config/index.js (No poner un valor por default)

2022-11-03 02:45 UTC, Soyelchamps commented on controllers/userControllers.js
> +      userid: user.id,
Se cambio por userId con la  I mayuscula

2022-11-03 03:34 UTC, servo98 approved these changes

2022-11-03 03:34 UTC, merged